export default {
  "76ers": { "cn": "费城76人", "short": "phi", "full": "Philadelphia 76ers", "en": "76ers" },
  "blazers": { "cn": "波特兰开拓者", "short": "por", "full": "Portland Trail Blazers", "en": "blazers" },
  "bucks": { "cn": "密尔沃基雄鹿", "short": "mil", "full": "Milwaukee Bucks", "en": "bucks" },
  "bulls": { "cn": "芝加哥公牛", "short": "chi", "full": "Chicago Bulls", "en": "bulls" },
  "cavaliers": { "cn": "克利夫兰骑士", "short": "cle", "full": "Cleveland Cavaliers", "en": "cavaliers" },
  "celtics": { "cn": "波士顿凯尔特人", "short": "bos", "full": "Boston Celtics", "en": "celtics" },
  "clippers": { "cn": "洛杉矶快船", "short": "lac", "full": "Los Angeles Clippers", "en": "clippers" },
  "grizzlies": { "cn": "孟菲斯灰熊", "short": "mem", "full": "Memphis Grizzlies", "en": "grizzlies" },
  "hawks": { "cn": "亚特兰大老鹰", "short": "atl", "full": "Atlanta Hawks", "en": "hawks" },
  "heat": { "cn": "迈阿密热火", "short": "mia", "full": "Miami Heat", "en": "heat" },
  "hornets": { "cn": "夏洛特黄蜂", "short": "cha", "full": "Charlotte Hornets", "en": "hornets" },
  "jazz": { "cn": "犹他爵士", "short": "uta", "full": "Utah Jazz", "en": "jazz" },
  "kings": { "cn": "萨克拉门托国王", "short": "sac", "full": "Sacramento Kings", "en": "kings" },
  "knicks": { "cn": "纽约尼克斯", "short": "nyk", "full": "New York Knicks", "en": "knicks" },
  "lakers": { "cn": "洛杉矶湖人", "short": "lal", "full": "Los Angeles Lakers", "en": "lakers" },
  "magic": { "cn": "奥兰多魔术", "short": "orl", "full": "Orlando Magic", "en": "magic" },
  "mavericks": { "cn": "达拉斯独行侠", "short": "dal", "full": "Dallas Mavericks", "en": "mavericks" },
  "nets": { "cn": "布鲁克林篮网", "short": "bkn", "full": "Brooklyn Nets", "en": "nets" },
  "nuggets": { "cn": "丹佛掘金", "short": "den", "full": "Denver Nuggets", "en": "nuggets" },
  "pacers": { "cn": "印第安纳步行者", "short": "ind", "full": "Indiana Pacers", "en": "pacers" },
  "pelicans": { "cn": "新奥尔良鹈鹕", "short": "nop", "full": "New Orleans Pelicans", "en": "pelicans" },
  "pistons": { "cn": "底特律活塞", "short": "det", "full": "Detroit Pistons", "en": "pistons" },
  "raptors": { "cn": "多伦多猛龙", "short": "tor", "full": "Toronto Raptors", "en": "raptors" },
  "rockets": { "cn": "休斯顿火箭", "short": "hou", "full": "Houston Rockets", "en": "rockets" },
  "spurs": { "cn": "圣安东尼奥马刺", "short": "sas", "full": "San Antonio Spurs", "en": "spurs" },
  "suns": { "cn": "菲尼克斯太阳", "short": "phx", "full": "Phoenix Suns", "en": "suns" },
  "thunder": { "cn": "俄克拉荷马城雷霆", "short": "okc", "full": "Oklahoma City Thunder", "en": "thunder" },
  "timberwolves": { "cn": "明尼苏达森林狼", "short": "min", "full": "Minnesota Timberwolves", "en": "timberwolves" },
  "warriors": { "cn": "金州勇士", "short": "gsw", "full": "Golden State Warriors", "en": "warriors" },
  "wizards": { "cn": "华盛顿奇才", "short": "was", "full": "Washington Wizards", "en": "wizards" }
}
